---
title: "About My Work"
description: |
  These are some projects I've been working on at Bren
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Master's Group Project

### Evaluating the Climate Mitigation Potential of Natural and Working Lands in Santa Barbara County

A team of 5 students working for the County of Santa Barbara to incorporate a natural and working lands (NWL) component into the Climate Action Plan update. Includes a carbon stock and emissions inventory, a projection to 2030, stakeholder engagement about carbon-smart management practices, and recommendations of how the County can promote future carbon sequestration through NWL management.

Check out our project website [here].
[here]: <https://carboncounters.weebly.com/>


***


## Carbon Accounting Project

### Bren Hall Climate Risk Assessment

A team of five students working on studying the climate-related risks to Bren Hall and the Bren community, with recommendations on how to mitigate potential damages.


***


## Corporate Sustainability Plan

### 5 Year Sustainability Roadmap for Dole Foods, Inc

A team of four students working on a sustainability plan, focused on food, people, and the environment, for Dole Foods.


